### ISSUE TITLE
Add support for "types" option

### ISSUE THREAD

**Issue by mglaman** [mglaman/intellij-drupal-run-tests#10]
```
  --types

              Runs just tests from the specified test type, for example
              run-tests.sh
              (i.e. --types "Simpletest,PHPUnit-Functional")
```

**Comment by jibran** [comment]
A follow up can be added to run [run-phantomjs.sh](https://gist.github.com/mglaman/f0cbe19a2fae4fb7f685c25606ab60ea#file-run-phantomjs-sh) for JS tests.

**Comment by mglaman** [comment]
I actually want to make a Phantom JS runner for IntelliJ platform.

**Comment by mglaman** [comment]
Done in @2e4f762dcdbcc9a475e5780660dff97541f2d197
