### ISSUE TITLE
Support "die-on-fail"

### ISSUE THREAD

**Issue by mglaman** [mglaman/intellij-drupal-run-tests#13]
```
  --die-on-fail

              Exit test execution immediately upon any failed assertion. This
              allows to access the test site by changing settings.php to use the
              test database and configuration directories. Use in combination
              with --repeat for debugging random test failures.
```

**Comment by jibran** [comment]
IMO "Simpletest database and files on fail" doesn't make sense tooltip text is helpful though "Test runner will exit on first failure and not do clean up for failed tests".
Maybe change it to "Abort test on fail and keep simpletest database and files."

**Comment by mglaman** [comment]
Thanks @jibran, I'll update. After I got off the plane I realized "that was a bad naming move"

**Comment by mglaman** [comment]
Updated
