### ISSUE TITLE
Invalid Drupal Directory configured for this project

### ISSUE THREAD

**Issue by juancasantito** [mglaman/intellij-drupal-run-tests#15]
Using 1.0-beta2, I get an error and cannot create a run configuration.

![selection_001](https://cloud.githubusercontent.com/assets/14225340/15945960/ed3f0f70-2e51-11e6-9b61-c7d32d1a8851.png)

**Comment by mglaman** [comment]
<img width="1018" alt="banners_and_alerts_and_invalid_drupal_directory_configured_for_this_project_ _issue__15_ _mglaman_intellij-drupal-run-tests" src="https://cloud.githubusercontent.com/assets/3698644/15946202/5f5a78e8-2e5b-11e6-89de-af3549e90edc.png">

Click "Fix" and setup Drupal integration with your project :)

**Comment by mglaman** [comment]
The screenshot on the README is old, I need to update it.

**Comment by juancasantito** [comment]
I just clicked the FIX option on my first try, it still does not work even though I did enable the Drupal Integration
![run-debug configurations_004](https://cloud.githubusercontent.com/assets/14225340/15948705/838ef6f4-2e5f-11e6-8c81-f57dbd02c964.png)

**Comment by mglaman** [comment]
:( Oh shoot. 

So basically it loads the Drupal integration information and gets the path to Drupal.

```
        DrupalDataService drupalDataService = DrupalDataService.getInstance(getProject());
        setWorkingDirectory(drupalDataService.getDrupalPath());
```

If that returns `null` the error and fix it is selected.

```
        if (PhpRunUtil.findDirectory(drupalRoot) == null) {
            throw new RuntimeConfigurationError("Invalid Drupal directory configured for this project.", createDrupalFix(getProject()));
        }
```

PhpStorm isn't throwing any warnings about the Drupal location?

**Comment by mglaman** [comment]
@juancasantito ~~I haven't been able to reproduce. The only way I've been able to reproduce is if there is no path saved to Drupal~~

I was able to produce! It's like the config form didn't recognize that the settings were changed.

**Comment by mglaman** [comment]
@juancasantito the fix is in for beta3/rc1, but for now
1. Fix the Drupal setting (Double check it is valid in Settings -> Language -> PHP -> Drupal)
2. Close the project
3. Reopen the project

Reopen if the above workaround doesn't solve the problem.
