### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by niccottrell** [mglaman/intellij-drupal-run-tests#16]
I'm having trouble getting the include paths setup properly in PhpStorm and Drupal 8. When trying to launch the tests, I get:

/usr/local/bin/php /Users/nic/git/cn-d8/core/scripts/run-tests.sh --php /usr/local/bin/php --url http://localhost:8080 --concurrency 1 --color --all
PHP Fatal error:  Interface 'Symfony\Component\DependencyInjection\ResettableContainerInterface' not found in /Users/nic/git/cn-d8/core/lib/Drupal/Component/DependencyInjection/Container.php on line 53

My paths include the /vender/X from composer, plus:

/core/lib
/core/modules
/modules

What steps am I missing?

**Comment by mglaman** [comment]
@niccottrell hm, so can your Drupal installation even run? The PHPStorm runner doesn't attempt to create its own test runner, but rather provides a GUI for configuring and executing `run-tests.sh`. It looks like you may need to run `composer install` from your Drupal root.

**Comment by niccottrell** [comment]
I guess I misunderstood the way this works. My local dev Drupal env doesn't seem to be configured correctly. I get the same error if I manually go to `/Users/me/git/d8` and run `php core/scripts/run-tests.sh --url http://localhost:8080`. I can run `run-tests.sh` from our development server.

**Comment by mglaman** [comment]
You need to run composer install. I'm going to try and update the requirement checks based on this.
