### ISSUE TITLE
Unselected test types in the UI output as 'null' in command parameter

### ISSUE THREAD

**Issue by davereid** [mglaman/intellij-drupal-run-tests#21]
If I only have 'Functional browser tests' checked in my configuration, the command is run with `--types PHPUnit-Functional,null,null,null,null`. It doesn't cause anything wrong, but it's worth noting that to others this will look strange.

**Comment by mglaman** [comment]
Yeah, that's me and Java fail. Should just pass non-null

**Comment by mglaman** [comment]
Here's the reason here, https://github.com/mglaman/intellij-drupal-run-tests/blob/master/src/com/mglaman/drupal_run_tests/run/tests/DrupalRunTestsSettingsEditor.java#L171.

I defined a String array with 5 keys. I forgot in Java it doesn't "reduce" if not all values are populated.

**Comment by mglaman** [comment]
Fixed!
