### ISSUE TITLE
Support Drupal 7?

### ISSUE THREAD

**Issue by mglaman** [mglaman/intellij-drupal-run-tests#4]

**Comment by jibran** [comment]
I think we can use remove "Drupal root" setting and use PHPstorm settings for root directory and Drupal version.

**Comment by mglaman** [comment]
I like that idea. Detect if it's a Drupal project, use the configured root.

**Comment by mglaman** [comment]
@jibran 💥 no more setting, it reads the Drupal config. Once I fix the concurrency spinner I'll probably tag new alpha, update plugin.

**Comment by jibran** [comment]
:clap: nicely done. Code changes looks awesome.
